{% set version = "0.5.1" %}

package:
  name: clint
  version: {{ version }}

source:
  fn: clint-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/clint/clint-{{ version }}.tar.gz
  md5: 8afd569f077886e2f4e6cca377da2623

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - args

  run:
    - python
    - args

test:
  imports:
    - clint
    - clint.packages
    - clint.packages.colorama
    - clint.textui

about:
  home: https://github.com/kennethreitz/clint
  license: ISC
  summary: 'Python Command Line Interface Tools'

extra:
  recipe-maintainers:
    - ericdill
    - SylvainCorlay
