# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "uP8ziYoErNbpXT3yugn5MsJrCNRCnbifpQaqYC29p1ZAQ63BqK6QKxs4ZJnuF/MmBgzw0XvoVsqRqCjCsLO4ZmzQuJPgle/pObVxCDqwfFdraA3VwWieRJgqvgaMQAx12dQMXttRvNnWx0XR/jlu4gmCxeIq9wBYQW2N6EO7pROtVBC3MdQjL0siVYOPGyKVlse+Hyrl3puHx1g8rrlaGHwylpCI1qZfpxCNvtlq1vn3y8ffyOdFp09FWSbmyNXhMFSAsveqXxlQTMZufAfyeJDnoTt+plUnN0gdyvvsRLWIO+5ry+gPkqBpr2udZKbUW2zHY0qduswhL4OjTyBIe9ZNYnkA0+JhAQqg3Gzh5dU2S3rDKcm31ipcEr2qVa2IEhb3eHeWIMWfKhZuZ7BHcsy76DiLYK72SbpZuTQQrmnz6vsxvg6iMZMbFPvsOuYnmurPwcG1LSSeKGpzAOdqKkzpTXdRudp/b/EpZjsXMrGTp2G/4VGmeU8H71G1I6CMN/x7DUzcQ3k1wKOG8hpFBp5do0BEaNKmt1D7lawBDBVacRdlI/H4ZU2YbZMYTkjJCLYFihb03zh1p55WsvTZlCkT/QuSaeM5JCE1mc79l8GFExBSkZIJD9ETwgZTPusfp01o0whtRV+ZiEI2McYB3WVGKWvQ60TTcDgv04PKUYo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
