travis:
  secure:
    BINSTAR_TOKEN: QywQSbJS2AI+k8OjuC2W5HRKlCO88LQLvBXIDQgsyW4p0qsQ1B4AWQF6Z5rjvf8LgX77T6qNz8NrLgs0MDRpGXPXeztEehT7LO6EnhDyumG4CvAjxvGL9DKyf6fFDrDa9w4XXMI41BTqgNImWhvZoJODmD+2g8jY6zfmG1Kzi/+dWm5ggXMd3+B77Di7OagtwS9PxZ/5PUOKiGUPUL+Z5La+PIQ8X6OovTWD1UPfCQLfhaNGmr+8zqLwhxkVxLh+5IA8O1vOLgqWSoF9yGj0g5KsucU71F2VeQ57spB6xHoTCWst4TxRpzYr2x/9Obx3kIa/DobNdqLGYRmJF0n/xjFqBhVjCUGqQmnmBobE+iPkb92bwxto/3T36vHctMcdLgp7OSZtao3a7m6waflpqu1es1MU+FZoWuQeZ+b/gdXI8mviYozuleqVBsoBY8/wHLyAtneEgzuWEV7Qp8wHGk/lCqV8WG4gb76WFM66kofXzaTd0Vlsvn+AjA8hsmwMb0VYZg5Rsjwwv0fhNgUHfj/4U35ky3rc0d6iiwNtHXv8TCZrjNCBThEKp8dY1oIkxGqH25dH6hyukG2QqqULFFsGxaNPuKtUKiEGIvhtWWdFxR5rXmnuml8wIBdRv6KM0xbiWy9STzvrqhesSb3sbawd8TNMoe2/5q+JQD1rsyI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
