travis:
  secure:
    BINSTAR_TOKEN: BQCoY2GOinrP8PCosHkQH51ftiCDLcGFurh3Y++wJULU4npxjwDDJRXZjj+yxwCKe5ws8PxfNJrKiU/MvEvaGee6Sx6wgMmxtpr2jSv1RzLholk8dx+/PPQdctqDdW/k9MpQTTV38asDuV3iiLxdvyzFD6oT4xAs8o+ARlB12r24VSsjGh6cIvh6KmaSDM6gSKnHEXdw10q+paFhcRc6INxmJKa8bmND/i7c0dKeOdTWlWUCpSkR7Yec+4snFfew8GMXw6/dQFLrr1sdlpzQ8Usdc6udQTVg/8Hm8y2zZAtWcVLu3ZxEvAPyYZuzg8SjgOCPJ3+ShW8i/aZh0XM8P9Ma8kwjnx0R/tOmH6t7szzxoSSFv9aT7JLrzLGAdb7aChLLprNoX9c2lNm+Iw0akeP0mO13iGKqAGD7vpsDTyehZfoGJiSu8YA0n0VsfQUmcPfnw3o6BB6vZ7uCxZcs+ukLi7DBSftggg6CFlOTHr9XphyYsmdIb3iQI1aP7V8voQcaFTvZrQoUHSa8XJhdG065nLr+SaM/pK/jx0gc3TOqfF3tgwCIEz4vD4UDhnv+vE77hBh84136iI6lwFe4Qr4aQwH2I597J4AefR4PR/pl7j7Qfr1qw0TnB2hI4oiu8vps1p6j6R85aTteMsoQi05aQGVOtRH5bLEORKRQZQM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
