travis:
  secure:
    BINSTAR_TOKEN: uP8ziYoErNbpXT3yugn5MsJrCNRCnbifpQaqYC29p1ZAQ63BqK6QKxs4ZJnuF/MmBgzw0XvoVsqRqCjCsLO4ZmzQuJPgle/pObVxCDqwfFdraA3VwWieRJgqvgaMQAx12dQMXttRvNnWx0XR/jlu4gmCxeIq9wBYQW2N6EO7pROtVBC3MdQjL0siVYOPGyKVlse+Hyrl3puHx1g8rrlaGHwylpCI1qZfpxCNvtlq1vn3y8ffyOdFp09FWSbmyNXhMFSAsveqXxlQTMZufAfyeJDnoTt+plUnN0gdyvvsRLWIO+5ry+gPkqBpr2udZKbUW2zHY0qduswhL4OjTyBIe9ZNYnkA0+JhAQqg3Gzh5dU2S3rDKcm31ipcEr2qVa2IEhb3eHeWIMWfKhZuZ7BHcsy76DiLYK72SbpZuTQQrmnz6vsxvg6iMZMbFPvsOuYnmurPwcG1LSSeKGpzAOdqKkzpTXdRudp/b/EpZjsXMrGTp2G/4VGmeU8H71G1I6CMN/x7DUzcQ3k1wKOG8hpFBp5do0BEaNKmt1D7lawBDBVacRdlI/H4ZU2YbZMYTkjJCLYFihb03zh1p55WsvTZlCkT/QuSaeM5JCE1mc79l8GFExBSkZIJD9ETwgZTPusfp01o0whtRV+ZiEI2McYB3WVGKWvQ60TTcDgv04PKUYo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
