travis:
  secure:
    BINSTAR_TOKEN: Sx+wf5hsqbaY9SEwmoxGU6PJL2hDf6GEPc6kcS4FcgnJjaeNQ0KLE3jUXRViO9aNUUN6VBzB2pckGeZYxHJ9ER4awTwg5OXwcvAVTNu0k/Haj8n3c8y8L7KkEUz6Zy+MbnfGSECYacGZQg2BB/JPB7M/hVixwxbNhQcxA3fEbh1j8Ww2rOafWAdtjWyzvEVW7NDGltVLEUbZRVFaT8q0TI6LCjHJ2cgvj85EwdkBjcL4trn/xupGCVMU79FJGo+Rm0g2ZadinEtg5lUKC4xrRUSoju1a6QSbVbV0VMdMPNlB02T2y7l2AAqIUv6uYXlWcr3qqQq+qObl184k+ir003NaAsJVkmmPm2I2ZGf2/lpl1EbhfPUEdNoY8gdAMokY0Qtp+eRasElpPGcV/hu4H1fh1vIWBGdZffNoEF/zKaa+gtQd/XZEJbK0kL9CfjqoYm+jPeYpdS0vmE9RwOiZ9cLw++/HPzeLVstWjk9fdsasP3irs7I0LMrMBmNxJmDpADNu1Oei5TRFaSdytrDMPga8DPZnIm3FitxPabF+G+VtZ1LllOteZBbsR8BYYmcMNAW6Km8GSGCFMa6TlHKlQ3IM8a4LWtUZQ6MHAEhv7NIoTRvqw3jVOShqrUgfdtiGpe/VqB6SQWi1MsuoUlpzsS0WJdIUZFCQ3zhCZHHXwZU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
